project = "Micro 2D Engine"
title = "The Micro 2D Engine Documentation"
description = "Micro 2D: The Code-Only 2D engine"
full_description = "Micro 2D acts as an abstraction layer built on top of Lua Player Plus, featuring an architecture inspired by Unity Engine.\n\nThis engine was custom-made for my game Tile Puzzle Ultimate (originally built with Unity) to provide a lightweight, bare-minimum feature set tailored for the Nintendo 3DS.\n\nBelow you can see all the modules available in the Micro 2D engine:"
file = {
    "./romfs/micro2d"
}
dir = "./doc"

all = true