project = "Micro2D Engine"
title = "The Micro2D Engine Documentation"
description = "Micro2D: The Code-Only 2D engine"
dir = "./doc"
format = "markdown"
all = true
full_description = "Micro2D acts as an abstraction layer built on top of Lua Player Plus, featuring an architecture inspired by Unity Engine.\n\nThis engine was custom-made for my game Tile Puzzle Ultimate (originally built with Unity), with the goal of offering a Unity-inspired structure and facilitating the port to the Nintendo 3DS.\n\nBelow you can see all the modules available in the Micro2D engine:"
file = {
    "./src/micro2d/banks",
    "./src/micro2d/components",
    "./src/micro2d/core",
    "./src/micro2d/debugger",
    "./src/micro2d/gameobject",
    "./src/micro2d/time",
    "./src/micro2d/systems",    
    "./src/micro2d/extender/math",
    "./src/micro2d/m2d_settings.lua",
}